{% set name = "arpack-mpi" %}
{% set version = "3.8.0" %}
{% set sha256 = "ada5aeb3878874383307239c9235b716a8a170c6d096a6625bfd529844df003d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/opencollab/arpack-ng/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - openmpi
    - lapack
    - openblas
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - liblapack
    - libopenblas

test:
  commands:
    - test -f ${PREFIX}/lib/libarpack.a
    - test -f ${PREFIX}/lib/libparpack.a
    - test -f ${PREFIX}/lib/libarpack${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libparpack${SHLIB_EXT}

about:
  home: https://github.com/opencollab/arpack-ng
  license: BSD-3-Clause
  license_file: COPYING
  summary: Fortran77 subroutines designed to solve large scale eigenvalue problems
